all:
#	mpicc -I/phys/linux/jlintuvu/codes/FFS/GIT/ffs/src/ffs -I/phys/linux/jlintuvu/codes/FFS/GIT/ffs/src/sim main_test.c -L/phys/linux/jlintuvu/codes/FFS/GIT/ffs/src -lffs -L/scratch/Juho/Code/mylammps/src/lib -llmp -lstdc++ -L/phys/linux/jlintuvu/codes/libu/lib -lu -lm

	mpicc -I/scratch/Juho/Code/ffs/src/ffs -I/phys/linux/jlintuvu/codes/FFS/GIT/ffs/src/sim main_test.c -L/scratch/Juho/Code/ffs/src -lffs -L/scratch/Juho/Code/mylammps/src/lib -llmp -lstdc++ -L/phys/linux/jlintuvu/codes/libu/lib -lu -lm

